version: '3'

services:
  app:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./topic_store:/app/topic_store
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped 